[tool.poetry]
name = "texting"
version = "0.0.3"
description = "misc for string"
authors = ["Hoyeung Wong <hoyeungw@outlook.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/pydget/texting.git"
repository = "https://github.com/pydget/texting.git"
keywords = [
    "str", "string", "ansi", "length",
    "pad", "tap", "str_value", "string_value"
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
