[tool.poetry]
name = "frattlesnake"
version = "0.1.2"
description = "frattlesnake is a bridge and library from KoLmafia's Java environment to a Python environment"
authors = ["Samuel Gaus <sam@gaus.co.uk>"]
readme = "README.md"
repository = "https://github.com/gausie/frattlesnake"

[tool.poetry.dependencies]
python = "^3.8"
pyjnius = "^1.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
