[tool.poetry]
name = "pytest-recordings"
version = "0.4.1"
description = "Provides pytest plugins for reporting request/response traffic, screenshots, and more to ReportPortal"
authors = ["Jonathan Castillo <jonathan.castillo@cloudcheckr.com>"]

[[tool.poetry.source]]
name = "public"
url = 'https://pypi.python.org/simple'

[tool.poetry.plugins."pytest11"]
"pytest_recordings" = "pytest_recordings.hooks"

[tool.poetry.dependencies]
python = ">=3.7"
vcrpy = "4.0.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"