[tool.poetry]
name = "fsu"
version = "2.0.0"
description = "FastAPI, SQLAlchemy core Utils and more"
authors = ["Lutz <lutz.l.burning@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
fastapi = ">=0.57.0 <1.0.0"
sqlalchemy = "^1.3.17"
orjson = "^3.0.1"
python-dateutil = "^2.8.1"
pyjwt = "^1.7.1"
aiohttp = "^3.6.2"
msgpack = "^1.0.0"

[tool.poetry.dev-dependencies]
uvicorn = "^0.11.5"
databases = "^0.3.2"
aiomysql = "^0.0.20"
alembic = "^1.4.2"
python-dotenv = "^0.13.0"
aioredis = "^1.3.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
